if(NOT DEFINED LIBRARY_ROOT)
    set(LIBRARY_ROOT "${CMAKE_CURRENT_LIST_DIR}")
endif()

file(GLOB_RECURSE types_files RELATIVE "${LIBRARY_ROOT}/types"
    "${LIBRARY_ROOT}/types/*")
foreach(path IN LISTS types_files)
    if(NOT path MATCHES "\\.h$" AND NOT path STREQUAL "README.md")
        message(FATAL_ERROR "types must contain declarations only: ${path}")
    endif()
    if(NOT path MATCHES "\\.h$")
        continue()
    endif()
    file(READ "${LIBRARY_ROOT}/types/${path}" source)
    string(REGEX REPLACE "/\\*([^*]|\\*+[^*/])*\\*+/" " " source "${source}")
    string(REGEX REPLACE "//[^\n]*" " " source "${source}")
    if(source MATCHES "#[ \t]*(if|ifdef|ifndef|elif)[^\n]*(^|[^A-Za-z0-9_])(_WIN32|WIN32|_WIN64|__linux__|__APPLE__)([^A-Za-z0-9_]|$)")
        message(FATAL_ERROR "types must not select an operating system: ${path}")
    endif()
    if(NOT path MATCHES "/")
        if(source MATCHES "lib/types/(win32|linux)/")
            message(FATAL_ERROR "Common types header imports platform vocabulary: ${path}")
        endif()
        string(REGEX MATCHALL "#[ \t]*include[ \t]*<[^>]+>" includes "${source}")
        foreach(line IN LISTS includes)
            if(NOT line MATCHES "<(assert|complex|ctype|errno|fenv|float|inttypes|iso646|limits|locale|math|setjmp|signal|stdalign|stdarg|stdatomic|stdbool|stddef|stdint|stdio|stdlib|stdnoreturn|string|tgmath|threads|time|uchar|wchar|wctype)\\.h>" AND
               NOT (path STREQUAL "atomic.h" AND line MATCHES "<intrin\\.h>"))
                message(FATAL_ERROR "Non-C declaration in common types header: ${path}: ${line}")
            endif()
        endforeach()
        if(NOT path STREQUAL "atomic.h" AND source MATCHES "_MSC_VER")
            message(FATAL_ERROR "Only atomic compiler adaptation is admitted: ${path}")
        endif()
    elseif(NOT path MATCHES "^(win32|linux)/[^/]+\\.h$")
        message(FATAL_ERROR "Unexpected types platform layout: ${path}")
    elseif(source MATCHES "(^|[^A-Za-z0-9_])(if|for|while|switch)[ \t\r\n]*\\(")
        message(FATAL_ERROR "Component control flow belongs outside types: ${path}")
    endif()
endforeach()

foreach(obsolete IN ITEMS win32.h posix.h clock.h input.h win32_runtime.h)
    if(EXISTS "${LIBRARY_ROOT}/types/${obsolete}")
        message(FATAL_ERROR "Obsolete types umbrella/dispatcher: ${obsolete}")
    endif()
endforeach()

file(GLOB_RECURSE library_sources RELATIVE "${LIBRARY_ROOT}"
    "${LIBRARY_ROOT}/*.c" "${LIBRARY_ROOT}/*.h")
foreach(path IN LISTS library_sources)
    file(STRINGS "${LIBRARY_ROOT}/${path}" includes REGEX "^[ \t]*#[ \t]*include")
    foreach(line IN LISTS includes)
        if(NOT path MATCHES "^types/" AND line MATCHES "#[ \t]*include[ \t]*<")
            message(FATAL_ERROR "External declarations bypass types: ${path}: ${line}")
        endif()
        if(line MATCHES "lib/types/(win32|linux)/")
            set(platform "${CMAKE_MATCH_1}")
            if(NOT path MATCHES "(^|/)${platform}/")
                message(FATAL_ERROR "Platform vocabulary crosses a neutral/other-platform boundary: ${path}")
            endif()
        endif()
        if(line MATCHES "lib/types/(win32|posix|clock|input|win32_runtime)\\.h")
            message(FATAL_ERROR "Obsolete types include: ${path}")
        endif()
    endforeach()
endforeach()
message(STATUS "types platform layout and declaration ownership verified")
