set(fixture "${CMAKE_CURRENT_BINARY_DIR}/product-boundary-fixture")
file(REMOVE_RECURSE "${fixture}")
file(MAKE_DIRECTORY "${fixture}/src/app" "${fixture}/src/vm" "${fixture}/src/compat")
file(WRITE "${fixture}/src/vm/vm_interface.h" "#include <common/machine/machine_interface.h>\n")
file(WRITE "${fixture}/src/app/main.c" "#include <vm/vm_interface.h>\n")
function(check expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DSOFTPC_SOURCE_DIR=${fixture}"
        -P "${SOFTPC_SOURCE_DIR}/test/support/product_boundary.cmake"
        RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
    if(expected STREQUAL "pass")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Legal composition rejected: ${error}")
        endif()
    elseif(result EQUAL 0 OR NOT error MATCHES "Product boundary")
        message(FATAL_ERROR "Illegal dependency accepted or wrong failure: ${error}")
    endif()
endfunction()
check(pass)
foreach(pair IN ITEMS "app/config.c|../vm/vm_interface.h" "app/main.c|compat/machine.h"
    "app/command.h|../compat/machine.h" "vm/vm_interface.h|compat/machine.h"
    "vm/driver.c|app/config.h" "compat/platform.c|common/machine/machine_interface.h")
    string(REPLACE "|" ";" parts "${pair}")
    list(GET parts 0 path)
    list(GET parts 1 header)
    file(WRITE "${fixture}/src/${path}" "#include \"${header}\"\n")
    check(fail)
    file(REMOVE "${fixture}/src/${path}")
endforeach()
file(REMOVE_RECURSE "${fixture}")
