# Product ownership, including relative include paths. Shared corpora are inputs,
# never modified by this product-specific check.
foreach(owner IN ITEMS app vm compat)
    file(GLOB_RECURSE sources "${SOFTPC_SOURCE_DIR}/src/${owner}/*.[ch]")
    foreach(source IN LISTS sources)
        file(RELATIVE_PATH relative "${SOFTPC_SOURCE_DIR}/src" "${source}")
        get_filename_component(directory "${source}" DIRECTORY)
        file(READ "${source}" contents)
        if(owner STREQUAL "app" AND contents MATCHES "softpc_machine_[A-Za-z0-9_]+[ \t]*\\(")
            message(FATAL_ERROR "Product boundary: raw machine call in ${relative}")
        endif()
        string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"][^>\"]+[>\"]" includes "${contents}")
        foreach(line IN LISTS includes)
            string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"]" "\\1" header "${line}")
            if(header MATCHES "^\\.\\.?/" OR EXISTS "${directory}/${header}")
                get_filename_component(target "${directory}/${header}" ABSOLUTE)
            else()
                get_filename_component(target "${SOFTPC_SOURCE_DIR}/src/${header}" ABSOLUTE)
            endif()
            file(RELATIVE_PATH dependency "${SOFTPC_SOURCE_DIR}/src" "${target}")
            if(owner STREQUAL "app")
                if(dependency MATCHES "^(compat|mvdm|host)/" OR
                   (dependency MATCHES "^vm/" AND NOT
                    (relative STREQUAL "app/main.c" AND dependency STREQUAL "vm/vm_interface.h")))
                    message(FATAL_ERROR "Product boundary: ${relative} -> ${dependency}")
                endif()
            elseif(owner STREQUAL "vm")
                if(dependency MATCHES "^app/" OR
                   (relative MATCHES "_interface\\.h$" AND dependency MATCHES "^(compat|mvdm|vm)/"))
                    message(FATAL_ERROR "Product boundary: ${relative} -> ${dependency}")
                endif()
            elseif(dependency MATCHES "^(app|vm|common)/")
                message(FATAL_ERROR "Product boundary: ${relative} -> ${dependency}")
            endif()
        endforeach()
    endforeach()
endforeach()
