if(NOT DEFINED SOFTPC_SOURCE_DIR OR NOT DEFINED TEST_WORK_DIR)
    message(FATAL_ERROR "SOFTPC_SOURCE_DIR and TEST_WORK_DIR required")
endif()
set(fixture "${TEST_WORK_DIR}/types-layout-fixture")
file(MAKE_DIRECTORY "${fixture}")
file(COPY "${SOFTPC_SOURCE_DIR}/src/lib/types" DESTINATION "${fixture}")
# A failed/aborted negative probe must not poison the next positive control.
# These are the only scratch files owned by this self-test.
file(REMOVE "${fixture}/consumer.c" "${fixture}/types/probe.h"
    "${fixture}/types/win32/probe.h")
set(probe "${fixture}/types/probe.h")
function(check_layout expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DLIBRARY_ROOT=${fixture}"
        -P "${SOFTPC_SOURCE_DIR}/src/lib/verify_types_layout.cmake"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(expected STREQUAL "pass" AND NOT status EQUAL 0)
        message(FATAL_ERROR "Valid layout rejected: ${output}${error}")
    elseif(expected STREQUAL "fail" AND status EQUAL 0)
        message(FATAL_ERROR "Invalid layout accepted")
    endif()
endfunction()
file(WRITE "${probe}" "#include <stdint.h>\n")
check_layout(pass)
file(WRITE "${probe}" "#ifdef _WIN32\n#endif\n")
check_layout(fail)
file(WRITE "${probe}" "#if defined(__linux__)\n#endif\n")
check_layout(fail)
file(WRITE "${probe}" "#include <windows.h>\n")
check_layout(fail)
file(WRITE "${probe}" "#include \"lib/types/win32/file.h\"\n")
check_layout(fail)
file(WRITE "${probe}" "#include <stdint.h>\n")
file(WRITE "${fixture}/types/win32/probe.h" "static inline int f(int x) { if (x) return 1; return 0; }\n")
check_layout(fail)
file(REMOVE "${fixture}/types/win32/probe.h")
file(WRITE "${fixture}/consumer.c" "#include \"lib/types/linux/file.h\"\n")
check_layout(fail)
file(WRITE "${fixture}/consumer.c" "#include <stdio.h>\n")
check_layout(fail)
foreach(token IN ITEMS HANDLE CreateEventA FILE fread pthread_mutex_t pthread_create VK_CONTROL UI_WIN32_KEY_CONTROL UINT64_MAX UINT_FAST16_MAX int_fast16_t pthread_condattr_t VK_UNKNOWN_UNWRAPPED)
    file(WRITE "${fixture}/consumer.c" "void probe(void) { ${token}; }\n")
    check_layout(fail)
endforeach()
foreach(call IN ITEMS realloc memmove GetUnwrappedOperation pthread_cond_timedwait)
    file(WRITE "${fixture}/consumer.c" "void probe(void) { ${call}(0); }\n")
    check_layout(fail)
endforeach()
file(WRITE "${fixture}/consumer.c" "#include \"lib/console/console.h\"\n")
check_layout(fail)
file(WRITE "${fixture}/consumer.c" "void probe(void) { lib_win32_handle h; }\n")
check_layout(pass)
file(REMOVE "${fixture}/consumer.c" "${probe}")
check_layout(pass)
