if(NOT DEFINED SOFTPC_SOURCE_DIR)
    message(FATAL_ERROR "SOFTPC_SOURCE_DIR is required")
endif()

set(component_root "${SOFTPC_SOURCE_DIR}/src/lib")
set(manifest "${component_root}/MANIFEST.sha256")
if(NOT EXISTS "${manifest}")
    message(FATAL_ERROR "Imported NXVM library manifest is missing")
endif()
file(SHA256 "${manifest}" manifest_hash)
string(TOUPPER "${manifest_hash}" manifest_hash)
if(NOT manifest_hash STREQUAL
    "53EE109E5FEFA31BA320321D9445122391CCD22C490AD7177651E8C4472BB6BC")
    message(FATAL_ERROR "Shared library manifest differs from the admitted T47 S4 corpus")
endif()
message(STATUS "Admitted T47 S4 shared library manifest is valid")
