if(NOT DEFINED SOFTPC_SOURCE_DIR)
    message(FATAL_ERROR "SOFTPC_SOURCE_DIR is required")
endif()

set(component_root "${SOFTPC_SOURCE_DIR}/src/lib/platform/win32")
set(manifest "${component_root}/MANIFEST.sha256")
if(NOT EXISTS "${manifest}")
    message(FATAL_ERROR "Win32 presentation manifest is missing")
endif()
file(STRINGS "${manifest}" entries REGEX "^[0-9A-Fa-f][0-9A-Fa-f].*  .+")
set(manifest_names)
foreach(entry IN LISTS entries)
    string(REGEX MATCH "^([0-9A-Fa-f]+)  (.+)$" matched "${entry}")
    set(expected "${CMAKE_MATCH_1}")
    set(name "${CMAKE_MATCH_2}")
    list(APPEND manifest_names "${name}")
    set(source "${component_root}/${name}")
    if(NOT EXISTS "${source}")
        message(FATAL_ERROR "Win32 presentation source is missing: ${name}")
    endif()
    file(READ "${source}" contents)
    string(REPLACE "\r\n" "\n" contents "${contents}")
    string(SHA256 actual "${contents}")
    string(TOUPPER "${actual}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Win32 presentation hash mismatch: ${name}")
    endif()
endforeach()
file(GLOB component_sources RELATIVE "${component_root}"
    "${component_root}/*.c" "${component_root}/*.h")
foreach(source IN LISTS component_sources)
    list(FIND manifest_names "${source}" manifest_index)
    if(manifest_index EQUAL -1)
        message(FATAL_ERROR "Win32 presentation manifest omits source: ${source}")
    endif()
endforeach()
message(STATUS "Win32 presentation component manifest is valid")
