#ifndef LIB_HOST_SYNC_INTERFACE_H
#define LIB_HOST_SYNC_INTERFACE_H

#include "lib/types/types_interface.h"

/* Host uses the neutral synchronization contract. These aliases preserve the
 * host-facing vocabulary while keeping all platform implementation in types. */
typedef lib_sync_wait_result host_sync_wait_result;
typedef lib_sync_event host_sync_event;
typedef lib_sync_task host_sync_task;
typedef lib_sync_task_entry host_sync_task_entry;

#define HOST_SYNC_WAIT_SIGNALED LIB_SYNC_WAIT_SIGNALED
#define HOST_SYNC_WAIT_CANCELLED LIB_SYNC_WAIT_CANCELLED
#define HOST_SYNC_WAIT_TIMED_OUT LIB_SYNC_WAIT_TIMED_OUT
#define HOST_SYNC_WAIT_INVALID_ARGUMENT LIB_SYNC_WAIT_INVALID_ARGUMENT
#define HOST_SYNC_WAIT_FAULT LIB_SYNC_WAIT_FAULT
#define host_sync_sleep_milliseconds lib_sync_sleep_milliseconds
#define host_sync_yield lib_sync_yield
#define host_sync_event_create lib_sync_event_create
#define host_sync_event_destroy lib_sync_event_destroy
#define host_sync_event_signal lib_sync_event_signal
#define host_sync_event_reset lib_sync_event_reset
#define host_sync_event_wait lib_sync_event_wait
#define host_sync_wait_any lib_sync_wait_any
#define host_sync_task_create lib_sync_task_create
#define host_sync_task_request_cancel lib_sync_task_request_cancel
#define host_sync_task_cancelled lib_sync_task_cancelled
#define host_sync_task_wait_cancel lib_sync_task_wait_cancel
#define host_sync_task_join lib_sync_task_join
#define host_sync_task_destroy lib_sync_task_destroy

#endif
