# Product ownership, including relative include paths. Shared corpora are inputs,
# never modified by this product-specific check.
foreach(owner IN ITEMS app-softpc/product app-softpc/machine app-softpc/compat common lib x86 app-softpc/softpc.new)
    file(GLOB_RECURSE sources "${SOFTPC_SOURCE_DIR}/src/${owner}/*.[ch]")
    foreach(source IN LISTS sources)
        file(RELATIVE_PATH relative "${SOFTPC_SOURCE_DIR}/src" "${source}")
        get_filename_component(directory "${source}" DIRECTORY)
        file(READ "${source}" contents)
        if(owner STREQUAL "app-softpc/product" AND contents MATCHES "softpc_machine_[A-Za-z0-9_]+[ \t]*\\(")
            message(FATAL_ERROR "Product boundary: raw machine call in ${relative}")
        endif()
        if(NOT owner STREQUAL "app-softpc/machine" AND contents MATCHES "vm_driver_(create|destroy)[ \t]*\\(")
            message(FATAL_ERROR "Product boundary: non-owning VM wrapper in ${relative}")
        endif()
        string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"][^>\"]+[>\"]" includes "${contents}")
        foreach(line IN LISTS includes)
            string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"]" "\\1" header "${line}")
            if(IS_ABSOLUTE "${header}")
                get_filename_component(target "${header}" ABSOLUTE)
            elseif(header MATCHES "^\\.\\.?/" OR EXISTS "${directory}/${header}")
                get_filename_component(target "${directory}/${header}" ABSOLUTE)
            elseif(owner STREQUAL "app-softpc/softpc.new" AND header MATCHES "^compat/")
                # Original controller includes resolve against their private Core root.
                get_filename_component(target "${SOFTPC_SOURCE_DIR}/src/app-softpc/${header}" ABSOLUTE)
            else()
                get_filename_component(target "${SOFTPC_SOURCE_DIR}/src/${header}" ABSOLUTE)
            endif()
            file(RELATIVE_PATH dependency "${SOFTPC_SOURCE_DIR}/src" "${target}")
            if(owner STREQUAL "app-softpc/product")
                if(dependency MATCHES "^host/" OR
                   (dependency MATCHES "^app-softpc/(machine|compat|softpc[.]new)/" AND NOT
                    (relative STREQUAL "app-softpc/product/composition.c" AND dependency STREQUAL "app-softpc/machine/vm_interface.h")))
                    message(FATAL_ERROR "Product boundary: ${relative} -> ${dependency}")
                endif()
            elseif(owner STREQUAL "app-softpc/machine")
                if(dependency MATCHES "^app-softpc/product/" OR
                   (relative MATCHES "_interface\\.h$" AND dependency MATCHES "^app-softpc/"))
                    message(FATAL_ERROR "Product boundary: ${relative} -> ${dependency}")
                endif()
            elseif(owner STREQUAL "app-softpc/compat")
                if(dependency MATCHES "^(app-softpc/(product|machine)|common|x86)/")
                    message(FATAL_ERROR "Product boundary: ${relative} -> ${dependency}")
                endif()
            elseif(dependency MATCHES "^app-softpc/" AND
                   NOT (owner STREQUAL "app-softpc/softpc.new" AND dependency MATCHES "^app-softpc/(softpc[.]new|compat)/"))
                message(FATAL_ERROR "Product boundary: ${relative} -> ${dependency}")
            elseif((owner STREQUAL "lib" AND dependency MATCHES "^(common|x86)/") OR
                   (owner STREQUAL "common" AND dependency MATCHES "^x86/") OR
                   (owner STREQUAL "app-softpc/softpc.new" AND dependency MATCHES "^(common|lib|x86)/"))
                message(FATAL_ERROR "Product boundary: ${relative} -> ${dependency}")
            endif()
        endforeach()
    endforeach()
endforeach()
