if(NOT DEFINED SOFTPC_SOURCE_DIR)
    message(FATAL_ERROR "SOFTPC_SOURCE_DIR is required")
endif()

set(component_root "${SOFTPC_SOURCE_DIR}/src/lib")
set(manifest "${component_root}/MANIFEST.sha256")
if(NOT EXISTS "${manifest}")
    message(FATAL_ERROR "Imported NXVM library manifest is missing")
endif()
execute_process(
    COMMAND "${CMAKE_COMMAND}" "-DLIBRARY_ROOT=${component_root}"
        -P "${component_root}/verify_manifest.cmake"
    RESULT_VARIABLE manifest_verify_result)
if(NOT manifest_verify_result EQUAL 0)
    message(FATAL_ERROR "Shared-library corpus manifest does not verify")
endif()
file(STRINGS "${manifest}" manifest_lines)
foreach(manifest_line IN LISTS manifest_lines)
    if(manifest_line MATCHES "^[0-9A-Fa-f]+  (.+)$")
        set(manifest_path "${CMAKE_MATCH_1}")
        if(manifest_path MATCHES "(^|/)internal/" OR manifest_path MATCHES "_internal\\.h$")
            message(FATAL_ERROR "Shared-library manifest retains private-directory path: ${manifest_path}")
        endif()
    endif()
endforeach()
message(STATUS "Shared-library manifest has no retired private-directory paths")
