[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$OriginalRoot,

    [string]$CurrentRoot = (Join-Path $PSScriptRoot '..\src\core\softpc')
)

$ErrorActionPreference = 'Stop'

$original = (Resolve-Path -LiteralPath $OriginalRoot).Path
$current = (Resolve-Path -LiteralPath $CurrentRoot).Path
$extensions = @('.c', '.h')
$records = [System.Collections.Generic.List[object]]::new()

function Get-Family([string]$RelativePath) {
    if ($RelativePath.StartsWith('base\ccpu386\')) { return 'CCPU' }
    if ($RelativePath.StartsWith('base\cvidc\')) { return 'C-VID' }
    if ($RelativePath.StartsWith('host\')) { return 'original host contract' }
    if ($RelativePath.StartsWith('base\bios\')) { return 'BIOS / firmware' }
    if ($RelativePath.StartsWith('base\video\')) { return 'video controller' }
    if ($RelativePath.StartsWith('base\disks\')) { return 'disk controller' }
    if ($RelativePath.StartsWith('base\keymouse\')) { return 'input controller' }
    if ($RelativePath.StartsWith('base\comms\')) { return 'communications controller' }
    if ($RelativePath.StartsWith('base\system\')) { return 'machine system' }
    if ($RelativePath.StartsWith('base\support\')) { return 'machine support' }
    return 'machine declarations'
}

function Get-NextTask([string]$Family, [bool]$HasOriginalPeer) {
    if (-not $HasOriginalPeer) { return 'M1 T2 / M2 placement review' }
    switch ($Family) {
        'CCPU' { return 'M1 T1 S2, then M1 T2' }
        'C-VID' { return 'M1 T1 S2, then M1 T2' }
        'original host contract' { return 'M2 host compatibility' }
        default { return 'M1 T1 S2' }
    }
}

function Get-Disposition([string]$RelativePath, [bool]$HasOriginalPeer) {
    if ($HasOriginalPeer) {
        if ($RelativePath.StartsWith('host\')) { return 'compat-host' }
        if ($RelativePath.StartsWith('base\ccpu386\') -or
            $RelativePath.StartsWith('base\cvidc\') -or
            $RelativePath.StartsWith('base\inc\')) {
            return 'port-abi-overlay'
        }
        if ($RelativePath -eq 'base\support\ios.c') { return 'compat-host' }
        return 'restore-pristine'
    }
    if ($RelativePath -eq 'base\ccpu386\softpc_ccpu_facade.c') {
        return 'compat-host'
    }
    if ($RelativePath -eq 'host\inc\softpc_standalone_dib.h') {
        return 'compat-host'
    }
    return 'port-abi-overlay'
}

function Get-CanonicalSource([string]$Path) {
    # The selected historical tree is CRLF while the working tree may be LF.
    # Source ownership is a text question, so do not report line-ending or
    # terminal-blank normalization as a machine divergence.
    $text = [System.Text.Encoding]::Latin1.GetString(
        [System.IO.File]::ReadAllBytes($Path)
    )
    return $text.Replace("`r", '').TrimEnd("`n")
}

Get-ChildItem -LiteralPath $current -Recurse -File |
    Where-Object { $_.Extension.ToLowerInvariant() -in $extensions } |
    Sort-Object FullName |
    ForEach-Object {
        $relative = $_.FullName.Substring($current.Length).TrimStart('\\')
        $originalPath = Join-Path $original $relative
        $hasPeer = Test-Path -LiteralPath $originalPath
        $state = 'no-original-peer'

        if ($hasPeer) {
            if ((Get-CanonicalSource $_.FullName) -ceq
                (Get-CanonicalSource $originalPath)) {
                return
            }
            $state = 'divergent-original-peer'
        }

        $markers = @(
            Select-String -LiteralPath $_.FullName `
                -Pattern 'SOFTPC_STANDALONE|softpc_standalone|runner_pacer|softpc_device_bop|softpc_gdp' `
                -AllMatches
        ).Count
        $family = Get-Family $relative
        $records.Add([PSCustomObject]@{
            Path = $relative.Replace('\\', '/')
            State = $state
            Family = $family
            Markers = $markers
            Disposition = Get-Disposition $relative $hasPeer
            NextTask = Get-NextTask $family $hasPeer
        })
    }

"# Pristine Divergence Manifest"
''
"Generated by `scripts/audit_pristine_divergence.ps1` from $(Split-Path -Leaf $original); it does not modify either tree."
''
'| Path | Baseline state | Family | Standalone markers | Disposition | Next task |'
'| --- | --- | --- | ---: | --- | --- |'
foreach ($record in $records) {
    "| ``$($record.Path)`` | $($record.State) | $($record.Family) | $($record.Markers) | $($record.Disposition) | $($record.NextTask) |"
}
''
"Total: $($records.Count)"
