#!/usr/bin/env python3
"""Rewrite C-VID generated GDP dereferences for a native-width host.

The original CPU_40 generator emits a 32-bit ``Gdp + offset`` ABI.  The
ordinary C sources already use the source-derived GDP side table; this tool
extends the same storage contract to generated ``sevid*.c`` rules without
modifying those source inputs.  It writes only the requested build output.
"""

from __future__ import annotations

import argparse
import pathlib
import re


STATIC_GDP = re.compile(
    r"\*\s*\(\s*\(\s*(?P<type>IUH)\s*\*\s*\)\s*"
    r"\(\s*r1\s*\+\s*(?P<offset>\d+)\s*\)\s*\)"
)

# Generated EDL emits this form when the original source selected a GDP field
# through a temporary rule register: *((TYPE *)((*((IHPE *)&r1)) + rNN)).
DYNAMIC_GDP = re.compile(
    r"\*\s*\(\s*\(\s*(?P<type>IUH|IU32|IU16|IU8|IS32|IS16|IS8|IHPE)\s*\*\s*\)\s*"
    r"\(\s*\(\s*\*\s*\(\s*\(\s*IHPE\s*\*\s*\)\s*"
    r"&\s*\(\s*r1\s*\)\s*\)\s*\)\s*\+\s*"
    r"\*\s*\(\s*\(\s*IHPE\s*\*\s*\)\s*"
    r"&\s*\(\s*(?P<offset_reg>r\d+)\s*\)\s*\)\s*\)\s*\)"
)

# A second generated form first places a historical GDP byte offset in a rule
# register, then dereferences that register directly.  At runtime the helper
# distinguishes these small legacy offsets from native pointers.
INDIRECT_GDP = re.compile(
    r"\*\s*\(\s*\(\s*(?P<type>IUH|IU32|IU16|IU8|IS32|IS16|IS8|IHPE)\s*\*\s*\)\s*"
    r"\(\s*\*\s*\(\s*\(\s*IHPE\s*\*\s*\)\s*"
    r"&\s*\(\s*(?P<address_reg>r\d+)\s*\)\s*\)\s*\)\s*\)"
)

# The generated translator measures this private stack in 32-bit IUH bytes.
# Its indexed accesses are IUH slots, so preserve the source slot count while
# allocating native-width storage on a 64-bit host.  Restrict this to the
# generated LocalIUH allocation; other malloc calls retain byte semantics.
LOCAL_IUH_MALLOC = re.compile(
    r"(?P<prefix>LocalIUH\s*=\s*\(\s*IUH\s*\*\s*\)\s*malloc\s*\(\s*)"
    r"(?P<bytes>\d+)(?P<suffix>\s*\))"
)


def static_replacement(match: re.Match[str]) -> str:
    return (
        "*((%s *)softpc_gdp_rule_slot((void *)r1, %su, sizeof(%s)))"
        % (match.group("type"), match.group("offset"), match.group("type"))
    )


def dynamic_replacement(match: re.Match[str]) -> str:
    value_type = match.group("type")
    offset_reg = match.group("offset_reg")
    return (
        "*((%s *)softpc_gdp_rule_slot((void *)r1, "
        "(unsigned int)(*((IHPE *)&(%s))), sizeof(%s)))"
        % (value_type, offset_reg, value_type)
    )


def indirect_replacement(match: re.Match[str]) -> str:
    value_type = match.group("type")
    address_reg = match.group("address_reg")
    return (
        "*((%s *)softpc_gdp_rule_address((void *)r1, "
        "(uintptr_t)(*((IHPE *)&(%s))), sizeof(%s)))"
        % (value_type, address_reg, value_type)
    )


def local_iuh_malloc_replacement(match: re.Match[str]) -> str:
    byte_count = int(match.group("bytes"))
    if byte_count % 4 != 0:
        raise ValueError("generated LocalIUH allocation is not word aligned")
    # Generated rules write 32-bit subregisters into these IUH slots and later
    # reload the full slot.  Zero initialization supplies the required x64
    # zero-extension for the otherwise unwritten upper half.
    return "%s%du, sizeof(IUH)%s" % (
        match.group("prefix").replace("malloc", "calloc"),
        byte_count // 4,
        match.group("suffix"),
    )


def transform_rules(source: str) -> tuple[str, int, int]:
    source, dynamic_count = DYNAMIC_GDP.subn(dynamic_replacement, source)
    source, static_count = STATIC_GDP.subn(static_replacement, source)
    source, _ = INDIRECT_GDP.subn(indirect_replacement, source)
    source, _ = LOCAL_IUH_MALLOC.subn(local_iuh_malloc_replacement, source)
    marker = '#include "softpc_gdp_rule_access.h"\n'
    if marker not in source:
        first_include_end = source.find("\n", source.find("#include")) + 1
        if first_include_end <= 0:
            raise ValueError("generated source has no include insertion point")
        source = source[:first_include_end] + marker + source[first_include_end:]
    return source, static_count, dynamic_count


def transform_event_glue(source: str) -> str:
    """Apply the narrow host-width ABI overlay to pristine event glue."""
    host_marker = '#include <stdio.h>\n#include <inttypes.h>\n'
    gdp_marker = '#include <softpc_gdp_slots.h>\n'
    if host_marker not in source:
        source = source.replace(
            '#include "host_def.h"\n',
            '#include "host_def.h"\n' + host_marker,
            1,
        )
    if gdp_marker not in source:
        source = source.replace(
            '#include "gdpvar.h"\t/* generated by build process */\n',
            '#include "gdpvar.h"\t/* generated by build process */\n' + gdp_marker,
            1,
        )
    source = source.replace(
        'chain %d\\n", chain_index',
        'chain %" PRIuPTR "\\n", (uintptr_t)chain_index',
    )
    source = source.replace(
        'write_bios_byte IFN2(IU8, eaVal, IU32, eaOff)',
        'write_bios_byte IFN2(ULONG, eaVal, ULONG, eaOff)',
    )
    source = source.replace(
        'write_bios_word IFN2(IU16, eaVal, IU32, eaOff)',
        'write_bios_word IFN2(ULONG, eaVal, ULONG, eaOff)',
    )
    source = source.replace(
        'Gdp = (IHP)host_malloc(64 * 1024);',
        'Gdp = (IHP)softpc_gdp_create();',
    )
    return source


def transform_ccpu_cpu4gen(source: str) -> str:
    """Overlay the selected CCPU generated header without changing its input."""
    marker = '#include <softpc_gdp_slots.h>\n'
    if marker not in source:
        source = source.replace(
            '#include <gdpvar.h>\t/* For direct access getAX() etc. */\n',
            '#include <gdpvar.h>\t/* For direct access getAX() etc. */\n' + marker,
            1,
        )
    for name in ('c_setCS', 'c_setSS', 'c_setDS', 'c_setES'):
        source = source.replace(
            'IMPORT\tIUH\t%s\tIPT1(IU16, val);' % name,
            'IMPORT\tISM32\t%s\tIPT1(IU16, val);' % name,
        )
    for name in ('c_getCF', 'c_getPF', 'c_getAF', 'c_getZF', 'c_getSF',
                 'c_getTF', 'c_getIF', 'c_getDF', 'c_getOF'):
        source = source.replace(
            'IMPORT\tIBOOL\t%s\tIPT0();' % name,
            'IMPORT\tISM32\t%s\tIPT0();' % name,
        )
    return source


def transform_ccpu_vglob(source: str) -> str:
    """Select the C-VID aggregate view and GDP slots outside pristine CCPU."""
    source = source.replace('#include "Evid_c.h"\n',
                            '#include "../cvidc/Evid_c.h"\n', 1)
    marker = '#include <softpc_gdp_slots.h>\n'
    if marker not in source:
        source = source.replace('#include "gdpvar.h"\n',
                                '#include "gdpvar.h"\n' + marker, 1)
    return source


def transform_ccpu_sas_header(source: str) -> str:
    marker = ('extern void sas_overwrite_memory IPT2(PHY_ADDR, addr, '
              'PHY_ADDR, len);\n')
    if marker not in source:
        source = source.replace('#include\t<sas4gen.h>\n',
                                '#include\t<sas4gen.h>\n\n' + marker, 1)
    source = re.sub(r'extern\s+(?:IHPE|sys_addr)\s+Length_of_M_area;[^\n]*',
                    'extern PHY_ADDR Length_of_M_area;\t/* guest physical byte count */',
                    source)
    return source


def transform_ccpu_bsic_header(source: str) -> str:
    marker = 'IMPORT IU32 c_getEFLAGS IPT0();\n'
    if marker not in source:
        source = source.replace('IMPORT IU32 getFLAGS IPT0();\n',
                                marker + '\nIMPORT IU32 getFLAGS IPT0();\n', 1)
    return source


def transform_ccpu_sas_source(source: str) -> str:
    includes = '#include <emm.h>\n#include <host.h>\n'
    if includes not in source:
        source = source.replace('#include <yoda.h>\n', '#include <yoda.h>\n' + includes, 1)
    declarations = ('extern UTINY *host_sas_init IPT1(sys_addr, size);\n'
                    'extern UTINY *host_sas_term IPT0();\n')
    if declarations not in source:
        source = source.replace('#include <host.h>\n', '#include <host.h>\n' + declarations, 1)
    return source


def transform_ccpu_main(source: str) -> str:
    if '#include <c_addr.h>' not in source:
        source = source.replace('#include <c_main.h>\t/* C CPU definitions-interfaces */\n',
                                '#include <c_main.h>\t/* C CPU definitions-interfaces */\n'
                                '#include <c_addr.h>\t/* C CPU address calculation contract */\n', 1)
    if '#include <c_seg.h>' not in source:
        source = source.replace('#include <c_mem.h>\t/* CPU - Memory Interface */\n',
                                '#include <c_mem.h>\t/* CPU - Memory Interface */\n'
                                '#include <c_seg.h>\t/* Segment-cache and pseudo-descriptor contract */\n', 1)
    if '#include <ica.h>' not in source:
        source = source.replace('#include <fault.h>\n',
                                '#include <fault.h>\n#include <ica.h>\n#include <timer.h>\n', 1)
    workers = '#include  <aaa.h>\t/* The workers */\n'
    declarations = ('extern void force_yoda(void);\n'
                    'extern void TakeNpxExceptionInt(void);\n')
    if declarations not in source:
        source = source.replace(workers, declarations + workers, 1)
    marker = '#define CCPU_INSTRUCTION_DELTA(x) ((IU32)DIFF_INST_BYTE((x), p_start))\n'
    if marker not in source:
        source = source.replace('#define UPDATE_INTEL_IP(x)', marker + '#define UPDATE_INTEL_IP(x)', 1)
    source = source.replace('   {  int len = DIFF_INST_BYTE(x, p_start);',
                            '   {  IU32 len = CCPU_INSTRUCTION_DELTA(x);', 1)
    source = source.replace('SET_EIP(GET_EIP() + DIFF_INST_BYTE(x, p_start) & WORD_MASK);',
                            'SET_EIP(GET_EIP() + (CCPU_INSTRUCTION_DELTA(x) & WORD_MASK));')
    source = source.replace('SET_EIP(GET_EIP() + DIFF_INST_BYTE(x, p_start));',
                            'SET_EIP(GET_EIP() + CCPU_INSTRUCTION_DELTA(x));')
    source = source.replace('SET_EIP(GET_EIP() + DIFF_INST_BYTE(*q, p_start));',
                            'SET_EIP(GET_EIP() + CCPU_INSTRUCTION_DELTA(*q));')
    return source


def transform_ccpu_ntstubs(source: str) -> str:
    source = source.replace('#include "evidgen.h"',
                            '#include "../cvidc/evidgen.h"', 1)
    if '#include <stdio.h>' not in source:
        source = source.replace('#include "cpu4.h"\n', '#include "cpu4.h"\n\n#include <stdio.h>\n', 1)
    source = source.replace('\nIHP Gdp;\nstruct CpuVector Cpu;',
                            '\nextern IHP Gdp;\nstruct CpuVector Cpu;', 1)
    for stub in ('void copyROM()\n{\n}\n',
                 'void initialise_npx()\n{\n}\n',
                 'void npx_reset()\n{\n}\n'):
        source = source.replace(stub, '', 1)
    return source


def transform_ccpu_fpu(source: str) -> str:
    if '#include <stdio.h>' not in source:
        source = source.replace('#include "host_def.h"\n',
                                '#include "host_def.h"\n#include <stdio.h>\n', 1)
    source = source.replace('reg_num += TOSPtr - FPUStackBase;',
                            'reg_num += (IU32)(TOSPtr - FPUStackBase);', 1)
    return source


def transform_ccpu_zfrsrvd(source: str) -> str:
    if '#include <c_addr.h>' not in source:
        source = source.replace('#include <c_mem.h>      /* CPU - Memory Interface */\n',
                                '#include <c_mem.h>      /* CPU - Memory Interface */\n'
                                '#include <c_addr.h>     /* Original d_mem/limit_check contracts */\n', 1)
    if '#include <c_intr.h>' not in source:
        source = source.replace('#include <c_reg.h>\n',
                                '#include <c_reg.h>\n#include <c_intr.h>     /* Original do_intrupt contract */\n'
                                '#include <intx.h>       /* Original INTx contract */\n', 1)
    declaration = 'GLOBAL VOID FLDENV IPT1(VOID *, memPtr);\n'
    if declaration not in source:
        source = source.replace('LOCAL VOID npx_fabs() {', declaration + '\nLOCAL VOID npx_fabs() {', 1)
    source = source.replace('VOID ZFRSRVD(npx_instr)\nIU32 npx_instr;\n{',
                            'VOID ZFRSRVD(IU32 npx_instr)\n{', 1)
    return source


def transform_ccpu_page(source: str) -> str:
    if '#include <yoda.h>' not in source:
        source = source.replace('#include <c_debug.h>\t/* Debugging Regs and Breakpoint interface */\n',
                                '#include <c_debug.h>\t/* Debugging Regs and Breakpoint interface */\n'
                                '#include <yoda.h>\n', 1)
    return source


def transform_ccpu_reg(source: str) -> str:
    if '#include <stdio.h>' not in source:
        source = source.replace('#include <Pigger_c.h>\n', '#include <Pigger_c.h>\n#include <stdio.h>\n', 1)
    return source


def transform_ccpu_xcptn(source: str) -> str:
    if '#include <yoda.h>' not in source:
        source = source.replace('#include <fault.h>\n', '#include <fault.h>\n#include <yoda.h>\n', 1)
    source = source.replace('\tIMPORT char *host_getenv IPT1 (char *, name);\t\t\t\\\n', '', 1)
    return source


def transform_ccpu_popf(source: str) -> str:
    if '#include <stdio.h>' not in source:
        source = source.replace('#include <host_def.h>\n', '#include <host_def.h>\n#include <stdio.h>\n', 1)
    declaration = 'extern void note_486_instruction(char *text);\n'
    if declaration not in source:
        source = source.replace('#include <config.h>\n', '#include <config.h>\n\n' + declaration, 1)
    return source


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    parser.add_argument("--report", type=pathlib.Path)
    parser.add_argument("--event-glue", action="store_true")
    parser.add_argument("--ccpu-cpu4gen", action="store_true")
    parser.add_argument("--ccpu-vglob", action="store_true")
    parser.add_argument("--ccpu-sas-header", action="store_true")
    parser.add_argument("--ccpu-bsic-header", action="store_true")
    parser.add_argument("--ccpu-sas-source", action="store_true")
    parser.add_argument("--ccpu-main", action="store_true")
    parser.add_argument("--ccpu-ntstubs", action="store_true")
    parser.add_argument("--ccpu-fpu", action="store_true")
    parser.add_argument("--ccpu-zfrsrvd", action="store_true")
    parser.add_argument("--ccpu-page", action="store_true")
    parser.add_argument("--ccpu-reg", action="store_true")
    parser.add_argument("--ccpu-xcptn", action="store_true")
    parser.add_argument("--ccpu-popf", action="store_true")
    args = parser.parse_args()

    original = args.source.read_text(encoding="latin-1")
    if args.event_glue:
        generated = transform_event_glue(original)
        static_count = dynamic_count = 1
    elif args.ccpu_cpu4gen:
        generated = transform_ccpu_cpu4gen(original)
        static_count = dynamic_count = 1
    elif args.ccpu_vglob:
        generated = transform_ccpu_vglob(original)
        static_count = dynamic_count = 1
    elif args.ccpu_sas_header:
        generated = transform_ccpu_sas_header(original)
        static_count = dynamic_count = 1
    elif args.ccpu_bsic_header:
        generated = transform_ccpu_bsic_header(original)
        static_count = dynamic_count = 1
    elif args.ccpu_sas_source:
        generated = transform_ccpu_sas_source(original)
        static_count = dynamic_count = 1
    elif args.ccpu_main:
        generated = transform_ccpu_main(original)
        static_count = dynamic_count = 1
    elif args.ccpu_ntstubs:
        generated = transform_ccpu_ntstubs(original)
        static_count = dynamic_count = 1
    elif args.ccpu_fpu:
        generated = transform_ccpu_fpu(original)
        static_count = dynamic_count = 1
    elif args.ccpu_zfrsrvd:
        generated = transform_ccpu_zfrsrvd(original)
        static_count = dynamic_count = 1
    elif args.ccpu_page:
        generated = transform_ccpu_page(original)
        static_count = dynamic_count = 1
    elif args.ccpu_reg:
        generated = transform_ccpu_reg(original)
        static_count = dynamic_count = 1
    elif args.ccpu_xcptn:
        generated = transform_ccpu_xcptn(original)
        static_count = dynamic_count = 1
    elif args.ccpu_popf:
        generated = transform_ccpu_popf(original)
        static_count = dynamic_count = 1
    else:
        generated, static_count, dynamic_count = transform_rules(original)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    # Ninja uses the output timestamp to decide whether every generated rule
    # must be compiled again.  A CMake reconfigure may re-invoke this command
    # even when its input is unchanged; do not turn that harmless invocation
    # into a full CCPU rebuild by rewriting identical output.
    if (not args.output.exists() or
            args.output.read_text(encoding="latin-1") != generated):
        args.output.write_text(generated, encoding="latin-1", newline="")
    if args.report is not None:
        args.report.write_text(
            "%s static=%d dynamic=%d\n"
            % (args.source.name, static_count, dynamic_count),
            encoding="ascii",
        )
    if static_count == 0 and dynamic_count == 0:
        raise ValueError("no recognized GDP dereference in " + str(args.source))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
