# Repository-local documentation and active-task governance gate.

function(softpc_fail message_text)
    message(FATAL_ERROR "Documentation governance: ${message_text}")
endfunction()

function(softpc_require_file root relative_path)
    if(NOT EXISTS "${root}/${relative_path}")
        softpc_fail("missing ${relative_path}")
    endif()
endfunction()

function(softpc_require_text root relative_path required_text)
    file(READ "${root}/${relative_path}" contents)
    string(FIND "${contents}" "${required_text}" found_at)
    if(found_at EQUAL -1)
        softpc_fail("${relative_path} must contain '${required_text}'")
    endif()
endfunction()

function(softpc_require_packet_field packet_body field_name)
    string(REGEX MATCH "\\|[ \\t]*${field_name}[ \\t]*\\|[ \\t]*[^| \\t][^|]*\\|"
        field_match "${packet_body}")
    if(field_match STREQUAL "")
        softpc_fail("active task packet must contain a non-empty '${field_name}' record")
    endif()
endfunction()

function(softpc_highest_history_identifier root pattern output_variable)
    file(GLOB_RECURSE records RELATIVE "${root}" "${root}/docs/history/*.md")
    set(highest 0)
    foreach(record IN LISTS records)
        if(record MATCHES "${pattern}")
            if(CMAKE_MATCH_1 GREATER highest)
                set(highest "${CMAKE_MATCH_1}")
            endif()
        endif()
    endforeach()
    set(${output_variable} "${highest}" PARENT_SCOPE)
endfunction()

function(softpc_highest_history_step root milestone task output_variable)
    file(GLOB_RECURSE records RELATIVE "${root}" "${root}/docs/history/*.md")
    set(highest 0)
    foreach(record IN LISTS records)
        if(record MATCHES "M${milestone}-T${task}-S([0-9]+)")
            if(CMAKE_MATCH_1 GREATER highest)
                set(highest "${CMAKE_MATCH_1}")
            endif()
        endif()
    endforeach()
    set(${output_variable} "${highest}" PARENT_SCOPE)
endfunction()

function(softpc_current_has_closed_task status task output_variable)
    string(REGEX MATCH "\\|[ \\t]*T${task}[ \\t]*\\|" closed_row "${status}")
    if(closed_row STREQUAL "")
        set(${output_variable} FALSE PARENT_SCOPE)
    else()
        set(${output_variable} TRUE PARENT_SCOPE)
    endif()
endfunction()

function(softpc_validate_queue_and_todo root active_proposal)
    file(READ "${root}/docs/states/QUEUE.md" queue)
    file(READ "${root}/docs/states/TODO.md" todo)
    if(NOT queue MATCHES "^# Queue")
        softpc_fail("docs/states/QUEUE.md must begin with '# Queue'")
    endif()
    if(NOT todo MATCHES "^# Long-Term Review Ledger")
        softpc_fail("docs/states/TODO.md must begin with '# Long-Term Review Ledger'")
    endif()
    if(queue MATCHES "[-*] ")
        softpc_fail("QUEUE.md must use an ordered list")
    endif()
    file(STRINGS "${root}/docs/states/QUEUE.md" queue_lines)
    foreach(queue_row IN LISTS queue_lines)
        if(NOT queue_row MATCHES "^[0-9]+\\. ")
            continue()
        endif()
        string(FIND "${queue_row}" "../proposals/" proposal_at)
        string(FIND "${queue_row}" ".md)" proposal_suffix_at)
        if(proposal_at EQUAL -1 OR proposal_suffix_at EQUAL -1)
            softpc_fail("every Queue entry must link to one proposal")
        endif()
    endforeach()
    file(GLOB proposal_files RELATIVE "${root}/docs/proposals"
        "${root}/docs/proposals/*.md")
    foreach(proposal_file IN LISTS proposal_files)
        set(proposal_link "../proposals/${proposal_file}")
        string(FIND "${queue}" "${proposal_link}" queue_hit)
        if(queue_hit EQUAL -1 AND NOT proposal_link STREQUAL "${active_proposal}")
            softpc_fail("proposal is neither queued nor active: ${proposal_file}")
        endif()
    endforeach()
    file(STRINGS "${root}/docs/states/TODO.md" todo_lines)
    foreach(todo_row IN LISTS todo_lines)
        if(NOT todo_row MATCHES "^- \\[ \\] ")
            continue()
        endif()
        if(NOT todo_row MATCHES "TODO\\((High|Medium|Low)\\)")
            softpc_fail("every TODO entry must declare TODO(High), TODO(Medium), or TODO(Low)")
        endif()
    endforeach()
endfunction()

function(softpc_validate_current_state root)
    file(READ "${root}/docs/states/CURRENT.md" status)
    foreach(heading IN ITEMS
        "# Project Status" "## Current Work" "## Current Technical Baseline"
        "## Recent M9 Closures" "## Recent Governance")
        string(FIND "${status}" "${heading}" heading_at)
        if(heading_at EQUAL -1)
            softpc_fail("CURRENT.md must contain '${heading}'")
        endif()
    endforeach()
    string(REGEX MATCHALL "## M[0-9]+ (T[0-9]+|Td) S[0-9]+ Packet" packet_headers "${status}")
    list(LENGTH packet_headers packet_count)
    string(FIND "${status}" "No implementation subtask is active." idle_at)
    if(NOT idle_at EQUAL -1)
        if(NOT packet_count EQUAL 0)
            softpc_fail("idle CURRENT.md must not retain an active packet")
        endif()
        set(active_proposal "")
    else()
        if(NOT packet_count EQUAL 1)
            softpc_fail("active CURRENT.md must contain exactly one task packet")
        endif()
        string(REGEX MATCH "## M([0-9]+) (T([0-9]+)|Td) S([0-9]+) Packet"
            packet_header "${status}")
        if(packet_header STREQUAL "")
            softpc_fail("active packet heading is malformed")
        endif()
        set(packet_milestone "${CMAKE_MATCH_1}")
        set(packet_kind "${CMAKE_MATCH_2}")
        set(packet_task "${CMAKE_MATCH_3}")
        set(packet_step "${CMAKE_MATCH_4}")
        string(FIND "${status}" "| Field | Required record |" table_header_at)
        string(FIND "${status}" "| --- | --- |" table_separator_at)
        if(table_header_at EQUAL -1 OR table_separator_at EQUAL -1)
            softpc_fail("active task packet must use the fixed Field table")
        endif()
        foreach(field IN ITEMS
            "Identifier Mode" "Admission And Approval" "Objective" "Non-goals"
            "Reference Baseline" "Candidate Proposal" "Files And ABI Surface"
            "Applicable Rules" "Verification" "Expected Markers" "Asset Needs"
            "Reporting Requirements" "Stop Conditions" "Exit Criteria"
            "Original Owner Request" "Similar-Issue Sweep")
            softpc_require_packet_field("${status}" "${field}")
        endforeach()
        string(REGEX MATCH "\\|[ \\t]*Identifier Mode[ \\t]*\\|[ \\t]*([^| \\t][^|]*)\\|"
            mode_row "${status}")
        set(identifier_mode "${CMAKE_MATCH_1}")
        string(STRIP "${identifier_mode}" identifier_mode)
        if(NOT identifier_mode MATCHES "^(New|Continuation|Corrective|Owner-Reopen|Governance)$")
            softpc_fail("Identifier Mode must be New, Continuation, Corrective, Owner-Reopen, or Governance")
        endif()
        string(REGEX MATCH "\\.\\./proposals/[^)]+\\.md" active_proposal "${status}")
        if(active_proposal STREQUAL "")
            softpc_fail("active packet must link its Candidate Proposal from docs/proposals/")
        endif()
        if(identifier_mode STREQUAL "Governance")
            if(NOT packet_kind STREQUAL "Td")
                softpc_fail("Governance mode requires a Td packet")
            endif()
            softpc_highest_history_identifier("${root}" "M${packet_milestone}-Td-S([0-9]+)" highest_td)
            math(EXPR expected_step "${highest_td} + 1")
            if(NOT packet_step EQUAL expected_step)
                softpc_fail("Governance packet must use the next Td S identifier (${expected_step})")
            endif()
        elseif(identifier_mode STREQUAL "New")
            if(packet_task STREQUAL "")
                softpc_fail("New mode requires a numeric T packet")
            endif()
            softpc_highest_history_identifier("${root}" "M[0-9]+-T([0-9]+)" highest_task)
            math(EXPR expected_task "${highest_task} + 1")
            if(NOT packet_task EQUAL expected_task OR NOT packet_step EQUAL 1)
                softpc_fail("New packet must use the next T identifier and S1")
            endif()
        else()
            if(packet_task STREQUAL "")
                softpc_fail("${identifier_mode} mode requires a numeric T packet")
            endif()
            softpc_highest_history_step("${root}" "${packet_milestone}" "${packet_task}" highest_step)
            if(highest_step EQUAL 0)
                softpc_fail("${identifier_mode} packet requires recorded history for its T identifier")
            endif()
            math(EXPR expected_step "${highest_step} + 1")
            if(NOT packet_step EQUAL expected_step)
                softpc_fail("${identifier_mode} packet must continue with the next S identifier (${expected_step})")
            endif()
            softpc_current_has_closed_task("${status}" "${packet_task}" task_is_closed)
            if(identifier_mode STREQUAL "Continuation")
                if(task_is_closed)
                    softpc_fail("Continuation mode cannot use a closed T identifier")
                endif()
            else()
                if(NOT task_is_closed)
                    softpc_fail("${identifier_mode} mode must reopen a recorded closed T identifier")
                endif()
                if(identifier_mode STREQUAL "Owner-Reopen")
                    string(TOLOWER "${mode_row}" mode_row_lower)
                    string(TOLOWER "${status}" status_lower)
                    if(NOT status_lower MATCHES "owner.*reopen|reopen.*owner")
                        softpc_fail("Owner-Reopen mode must record the owner reopen approval")
                    endif()
                endif()
            endif()
        endif()
    endif()
    if(NOT status MATCHES "\\| T[0-9]+ \\|")
        softpc_fail("CURRENT.md must retain a compact numeric task closure row")
    endif()
    string(REGEX MATCHALL "- \\*\\*M[0-9]+ Td S[0-9]+:" governance_rows "${status}")
    list(LENGTH governance_rows governance_count)
    if(governance_count GREATER 8)
        softpc_fail("CURRENT.md must retain at most eight recent governance rows")
    endif()
    softpc_validate_queue_and_todo("${root}" "${active_proposal}")
endfunction()

function(softpc_validate_repository root)
    file(REAL_PATH "${root}" root)
    foreach(required_directory IN ITEMS
        docs/design docs/rules docs/states docs/proposals docs/history docs/etc)
        if(NOT IS_DIRECTORY "${root}/${required_directory}")
            softpc_fail("missing ${required_directory}/")
        endif()
    endforeach()
    foreach(required_file IN ITEMS
        AGENTS.md CONTRIBUTING.md docs/README.md docs/etc/README.md
        docs/design/GOAL.md docs/design/ARCHITECTURE.md docs/design/CODING.md
        docs/design/UI.md docs/design/ROADMAP.md
        docs/rules/DOCUMENT.md docs/rules/EXECUTION.md
        docs/rules/ARCHITECTURE.md docs/rules/CODING.md
        docs/states/CURRENT.md docs/states/QUEUE.md docs/states/TODO.md)
        softpc_require_file("${root}" "${required_file}")
    endforeach()
    softpc_require_text("${root}" "docs/README.md" "states/CURRENT.md")
    softpc_require_text("${root}" "docs/README.md" "rules/EXECUTION.md")
    softpc_require_text("${root}" "docs/etc/README.md" "Supporting Material Index")
    softpc_require_text("${root}" "docs/rules/EXECUTION.md" "Identifier Mode")
    softpc_require_file("${root}" "docs/etc/operations/policy/source-research-policy.md")
    softpc_require_text("${root}" "docs/etc/operations/policy/source-research-policy.md"
        "## External Source Admission")
    softpc_require_text("${root}" "docs/etc/operations/policy/source-research-policy.md"
        "## License Decision Boundary")
    softpc_require_text("${root}" "docs/etc/operations/policy/source-research-policy.md"
        "## Legacy Material Boundary")
    softpc_require_text("${root}" "docs/rules/ARCHITECTURE.md"
        "Source And Research Policy")
    softpc_require_text("${root}" "AGENTS.md" "build version")
    file(GLOB top_level_documents LIST_DIRECTORIES false "${root}/docs/*.md")
    foreach(document_path IN LISTS top_level_documents)
        get_filename_component(document_name "${document_path}" NAME)
        if(NOT document_name STREQUAL "README.md")
            softpc_fail("docs/${document_name} must be placed in its authority directory")
        endif()
    endforeach()
    softpc_validate_current_state("${root}")
endfunction()

function(softpc_write_fixture root state_body queue_body todo_body)
    file(MAKE_DIRECTORY "${root}/docs/design" "${root}/docs/rules"
        "${root}/docs/states" "${root}/docs/proposals" "${root}/docs/history"
        "${root}/docs/etc/operations/policy")
    file(WRITE "${root}/AGENTS.md" "build version\n")
    file(WRITE "${root}/CONTRIBUTING.md" "contributing\n")
    file(WRITE "${root}/docs/README.md" "states/CURRENT.md\nrules/EXECUTION.md\n")
    file(WRITE "${root}/docs/etc/README.md" "Supporting Material Index\n")
    file(WRITE "${root}/docs/etc/operations/policy/source-research-policy.md"
        "## External Source Admission\n\nsource\n\n## Legacy Material Boundary\n\nlegacy\n\n## License Decision Boundary\n\nlicense\n")
    foreach(document IN ITEMS GOAL ARCHITECTURE CODING UI ROADMAP)
        file(WRITE "${root}/docs/design/${document}.md" "${document}\n")
    endforeach()
    file(WRITE "${root}/docs/rules/DOCUMENT.md" "document\n")
    file(WRITE "${root}/docs/rules/EXECUTION.md" "Identifier Mode\n")
    file(WRITE "${root}/docs/rules/ARCHITECTURE.md" "Source And Research Policy\n")
    file(WRITE "${root}/docs/rules/CODING.md" "coding\n")
    file(WRITE "${root}/docs/states/CURRENT.md" "${state_body}")
    file(WRITE "${root}/docs/states/QUEUE.md" "${queue_body}")
    file(WRITE "${root}/docs/states/TODO.md" "${todo_body}")
    file(WRITE "${root}/docs/proposals/active.md" "active\n")
endfunction()

function(softpc_expect_fixture fixture expected_success)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DSOFTPC_SOURCE_DIR=${fixture}"
        -P "${CMAKE_CURRENT_LIST_FILE}" RESULT_VARIABLE result)
    if(expected_success AND NOT result EQUAL 0)
        softpc_fail("self-test expected accepted fixture to pass")
    endif()
    if(NOT expected_success AND result EQUAL 0)
        softpc_fail("self-test expected rejected fixture to fail")
    endif()
endfunction()

if(SELF_TEST)
    if(NOT DEFINED SELF_TEST_ROOT)
        softpc_fail("SELF_TEST_ROOT is required for verifier self-tests")
    endif()
    set(packet "# Project Status\n\n## Current Work\n\nM9 Td S1 is active.\n\n## Current Technical Baseline\n\nbaseline\n\n## Recent M9 Closures\n\n| Task | Closure | Evidence |\n| --- | --- | --- |\n| T1 | closed | evidence |\n\n## Recent Governance\n\n## M9 Td S1 Packet\n\n| Field | Required record |\n| --- | --- |\n| Identifier Mode | Governance |\n| Admission And Approval | owner |\n| Objective | objective |\n| Non-goals | none |\n| Reference Baseline | baseline |\n| Candidate Proposal | [active](../proposals/active.md) |\n| Files And ABI Surface | docs |\n| Applicable Rules | rules |\n| Verification | test |\n| Expected Markers | markers |\n| Asset Needs | none |\n| Reporting Requirements | report |\n| Stop Conditions | stop |\n| Exit Criteria | exit |\n| Original Owner Request | request |\n| Similar-Issue Sweep | sweep |\n")
    set(queue "# Queue\n\n1. [active](../proposals/active.md)\n")
    set(todo "# Long-Term Review Ledger\n\nNo deferred work.\n")
    softpc_write_fixture("${SELF_TEST_ROOT}/valid" "${packet}" "${queue}" "${todo}")
    softpc_expect_fixture("${SELF_TEST_ROOT}/valid" TRUE)
    softpc_write_fixture("${SELF_TEST_ROOT}/missing-source-policy" "${packet}" "${queue}" "${todo}")
    file(REMOVE "${SELF_TEST_ROOT}/missing-source-policy/docs/etc/operations/policy/source-research-policy.md")
    softpc_expect_fixture("${SELF_TEST_ROOT}/missing-source-policy" FALSE)
    string(REPLACE "| Objective | objective |" "| Objective | |" missing_field "${packet}")
    softpc_write_fixture("${SELF_TEST_ROOT}/missing-field" "${missing_field}" "${queue}" "${todo}")
    softpc_expect_fixture("${SELF_TEST_ROOT}/missing-field" FALSE)
    softpc_write_fixture("${SELF_TEST_ROOT}/orphan-proposal" "${packet}" "${queue}" "${todo}")
    file(WRITE "${SELF_TEST_ROOT}/orphan-proposal/docs/proposals/orphan.md" "orphan\n")
    softpc_expect_fixture("${SELF_TEST_ROOT}/orphan-proposal" FALSE)
    softpc_write_fixture("${SELF_TEST_ROOT}/bad-todo" "${packet}" "${queue}"
        "# Long-Term Review Ledger\n\n- [ ] debt\n")
    softpc_expect_fixture("${SELF_TEST_ROOT}/bad-todo" FALSE)
    string(REPLACE "| Identifier Mode | Governance |" "| Identifier Mode | New |"
        invalid_mode "${packet}")
    softpc_write_fixture("${SELF_TEST_ROOT}/invalid-identifier" "${invalid_mode}" "${queue}" "${todo}")
    softpc_expect_fixture("${SELF_TEST_ROOT}/invalid-identifier" FALSE)
    message(STATUS "SoftPC documentation governance self-tests passed")
else()
    if(NOT DEFINED SOFTPC_SOURCE_DIR)
        softpc_fail("SOFTPC_SOURCE_DIR must name the repository root")
    endif()
    softpc_validate_repository("${SOFTPC_SOURCE_DIR}")
    message(STATUS "SoftPC documentation governance checks passed")
endif()
