cmake_minimum_required(VERSION 3.23)
if(NOT DEFINED PRODUCT_ROOT)
    set(PRODUCT_ROOT "${CMAKE_CURRENT_LIST_DIR}")
endif()
set(components debug xasm32 surface)
set(edges_debug emulator/machine common/machine product/xasm32 lib/storage lib/types)
set(edges_xasm32 lib/types)
set(edges_surface emulator/machine emulator/session emulator/ui common/machine common/session common/ui product/debug lib/kvm-base lib/types)

file(READ "${PRODUCT_ROOT}/CMakeLists.txt" product_build)
if(product_build MATCHES "(^|[^A-Za-z0-9_-])(x86|ibmpc)-")
    message(FATAL_ERROR "Product build must not link retained x86 or ibmpc targets")
endif()

function(check_edge owner dependency)
    if(NOT dependency STREQUAL "product/${owner}" AND NOT dependency IN_LIST edges_${owner})
        message(FATAL_ERROR "Forbidden Product edge: ${owner} -> ${dependency}")
    endif()
endfunction()

file(GLOB_RECURSE paths RELATIVE "${PRODUCT_ROOT}" "${PRODUCT_ROOT}/*")
foreach(path IN LISTS paths)
    if(path MATCHES "(^|/)(win32|linux)(/|$)")
        message(FATAL_ERROR "Product must not contain platform directories: ${path}")
    endif()
    if(NOT path MATCHES "^(debug|xasm32|surface)/[^/]+\\.[ch]$")
        continue()
    endif()
    set(owner "${CMAKE_MATCH_1}")
    file(READ "${PRODUCT_ROOT}/${path}" source)
    string(REGEX REPLACE "\"[^\"]*\"" "" tokens "${source}")
    string(REGEX REPLACE "/\\*([^*]|\\*+[^*/])*\\*+/" "" tokens "${tokens}")
    string(REGEX REPLACE "//[^\n]*" "" tokens "${tokens}")
    if(tokens MATCHES "_WIN32|_WIN64|__linux__|WINAPI|CRITICAL_SECTION|WaitForSingleObject|CreateEvent[A-W]?|pthread_")
        message(FATAL_ERROR "Platform implementation in Product: ${path}")
    endif()
    string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"][^>\"]+[>\"]" includes "${source}")
    foreach(include IN LISTS includes)
        string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"]" "\\1" header "${include}")
        if(NOT header MATCHES "^(product|common|emulator|lib)/[^/]+/[^/]+\\.h$")
            message(FATAL_ERROR "Noncanonical Product include: ${header}")
        endif()
        string(REGEX MATCH "^([^/]+)/([^/]+)/([^/]+\\.h)$" _ "${header}")
        set(dependency "${CMAKE_MATCH_1}/${CMAKE_MATCH_2}")
        set(file "${CMAKE_MATCH_3}")
        check_edge("${owner}" "${dependency}")
        if(dependency STREQUAL "product/${owner}")
            if(NOT EXISTS "${PRODUCT_ROOT}/${owner}/${file}")
                message(FATAL_ERROR "Missing local Product header: ${header}")
            endif()
        elseif(NOT dependency STREQUAL "lib/types" AND NOT file MATCHES "_interface\\.h$")
            message(FATAL_ERROR "Private dependency in Product: ${header}")
        endif()
    endforeach()
endforeach()
message(STATUS "Product platform and component boundaries verified")
